# Generated by Django 2.1.3 on 2019-06-18 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sharedstrings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('first_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sharedstrings.Strings')),
                ('last_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sharedstrings.Strings')),
                ('merged_into', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='merges_from', to='retconpeople.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sharedstrings.Strings')),
            ],
        ),
        migrations.CreateModel(
            name='UserNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sharedstrings.Strings')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=255)),
                ('user_name_pattern', models.CharField(max_length=1024, null=True)),
                ('user_number_pattern', models.CharField(max_length=1024, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sharedstrings.Strings')),
                ('tld', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sharedstrings.Strings')),
            ],
        ),
        migrations.AddField(
            model_name='usernumber',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_numbers', to='retconpeople.Website'),
        ),
        migrations.AddField(
            model_name='username',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_names', to='retconpeople.Website'),
        ),
    ]
