# Generated by Django 2.1.3 on 2019-09-22 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retconpeople', '0008_auto_20190920_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sharedstrings.Strings'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sharedstrings.Strings'),
        ),
        migrations.AlterField(
            model_name='person',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='merges_from', to='retconpeople.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pseudonyms',
            field=models.ManyToManyField(blank=True, related_name='_person_pseudonyms_+', to='sharedstrings.Strings'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='_person_tags_+', to='semantictags.Tag'),
        ),
    ]
