# Generated by Django 2.1.3 on 2019-09-30 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retconpeople', '0009_auto_20190922_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='merged_from', to='retconpeople.Person'),
        ),
    ]
