# Generated by Django 2.1.1 on 2019-10-07 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retconpeople', '0010_auto_20190930_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernumber',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_numbers', to='retconpeople.Website'),
        ),
    ]
