# Generated by Django 2.1.3 on 2019-12-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotables', '0001_initial'),
        ('retconpeople', '0015_auto_20191124_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='external_representation',
            field=models.ManyToManyField(to='remotables.ContentResource'),
        ),
    ]
