# Generated by Django 2.1.3 on 2019-12-31 23:49

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
        MyModel = apps.get_model('retconpeople', 'Person')
        for row in MyModel.objects.all():
            row.uuid = uuid.uuid4()
            row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    
            
    dependencies = [
        ('retconpeople', '0020_person_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='person',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4,unique=True),
        )
        
    ]
