# Generated by Django 2.1.3 on 2020-07-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconpeople', '0026_auto_20200630_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='distinguish_from',
            field=models.ManyToManyField(help_text='Indicate people of similar names who should not be confused', related_name='_person_distinguish_from_+', to='retconpeople.Person'),
        ),
    ]
