# Generated by Django 2.2.14 on 2021-05-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconpeople', '0031_auto_20210524_2336'),
        ('retconstorage','0007_auto_20200612_2121')
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='in_photos',
            field=models.ManyToManyField(blank=True, related_name='_person_in_photos_+', to='retconstorage.ManagedFile'),
        ),
        migrations.AlterField(
            model_name='person',
            name='potentially_in_photos',
            field=models.ManyToManyField(blank=True, related_name='_person_potentially_in_photos_+', to='retconstorage.ManagedFile'),
        ),
        migrations.AlterField(
            model_name='person',
            name='solo_photos',
            field=models.ManyToManyField(blank=True, related_name='_person_solo_photos_+', to='retconstorage.ManagedFile'),
        ),
    ]
