# Generated by Django 2.2.14 on 2021-09-20 22:42

from django.db import migrations, models
import django.db.models.deletion


def copy_website_company_to_comany_website(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Company = apps.get_model("retconcreatives", "Company")
    Website = apps.get_model("retconpeople", "Website")
    db_alias = schema_editor.connection.alias
    cl=Company.objects.filter(website__isnull=False)
    for c in cl:
        w=c.website
        w.owner=c
        w.save()

def copy_website_company_to_comany_website_reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0038_auto_20200906_2030'),
        ('retconpeople', '0032_auto_20210524_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='websites', to='retconcreatives.Company'),
        ),
        migrations.RunPython(copy_website_company_to_comany_website,copy_website_company_to_comany_website_reverse),
    ]
