# Generated by Django 2.1.3 on 2020-01-05 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retconstorage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MIME', models.CharField(max_length=64)),
                ('UTI', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='managedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='collection',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='_collection_parents_+', to='retconstorage.Collection'),
        ),
        migrations.AddField(
            model_name='managedfile',
            name='md5',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managedfile',
            name='sha256',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectionmetadata',
            name='collection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='retconstorage.Collection'),
        ),
        migrations.AlterField(
            model_name='collectionmetadata',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AddField(
            model_name='managedfile',
            name='filetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='retconstorage.Filetype'),
        ),
    ]
