# Generated by Django 2.1.3 on 2020-06-04 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retconstorage', '0002_auto_20200105_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, null=True)),
                ('inode', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('identity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='retconstorage.ManagedFile')),
            ],
        ),
    ]
