# Generated by Django 2.1.3 on 2020-06-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconstorage', '0004_auto_20200610_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedfile',
            name='retain_count',
            field=models.IntegerField(default=0, help_text='Positive indicates desire to keep, negative to delete,0=inbox'),
        ),
        migrations.AddField(
            model_name='managedfile',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managedfile',
            name='storage_status',
            field=models.CharField(blank=True, choices=[('m', 'Missing'), ('h', 'Have'), ('d', 'Deleted')], max_length=1, null=True),
        ),
    ]
