# Generated by Django 2.1.3 on 2020-06-11 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retconstorage', '0005_auto_20200610_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedCollectionMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_members', to='retconstorage.Collection')),
                ('managed_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='retconstorage.ManagedFile')),
            ],
        ),
    ]
