# Generated by Django 2.2.28 on 2023-07-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconstorage', '0009_auto_20230715_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmetadata',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
