# Generated by Django 2.1.3 on 2019-06-18 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sharedstrings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_sensitive_name', models.BooleanField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sharedstrings.Strings')),
                ('parent_studio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='retconcreatives.Studio')),
            ],
        ),
    ]
