# Generated by Django 2.1.3 on 2019-06-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharedstrings', '0001_initial'),
        ('retconpeople', '0004_auto_20190618_1148'),
        ('retconcreatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='retconpeople.Person')),
            ],
            bases=('retconpeople.person',),
        ),
        migrations.CreateModel(
            name='CreativeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('creativework_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='retconcreatives.CreativeWork')),
            ],
            bases=('retconcreatives.creativework',),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('creativework_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='retconcreatives.CreativeWork')),
                ('medium', models.PositiveSmallIntegerField(choices=[(0, 'Anthology'), (2, 'Audio'), (3, 'Comic book / Manga'), (1, 'Book'), (4, 'Movie'), (6, 'Software'), (5, 'Television'), (7, 'Video Game'), (8, 'Webcomic'), (9, 'Webseries')])),
            ],
            bases=('retconcreatives.creativework',),
        ),
        migrations.AddField(
            model_name='actor',
            name='acted_in_series',
            field=models.ManyToManyField(to='retconcreatives.Series'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('episode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='retconcreatives.Episode')),
            ],
            bases=('retconcreatives.episode',),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('episode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='retconcreatives.Episode')),
            ],
            bases=('retconcreatives.episode',),
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('episode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='retconcreatives.Episode')),
            ],
            bases=('retconcreatives.episode',),
        ),
        migrations.CreateModel(
            name='WebVideo',
            fields=[
                ('episode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='retconcreatives.Episode')),
            ],
            bases=('retconcreatives.episode',),
        ),
        migrations.AddField(
            model_name='episode',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sharedstrings.Strings'),
        ),
        migrations.AddField(
            model_name='episode',
            name='part_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='retconcreatives.Series'),
        ),
        migrations.CreateModel(
            name='Comicbook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='retconcreatives.Book')),
            ],
            bases=('retconcreatives.book',),
        ),
        migrations.CreateModel(
            name='TVEpisode',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='retconcreatives.Movie')),
            ],
            bases=('retconcreatives.movie',),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='reading_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='retconcreatives.Book'),
        ),
        migrations.AddField(
            model_name='actor',
            name='acted_in_movies',
            field=models.ManyToManyField(to='retconcreatives.Movie'),
        ),
    ]
