# Generated by Django 2.1.3 on 2019-06-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0005_auto_20190622_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativework',
            name='tags',
            field=models.ManyToManyField(to='semantictags.Tag'),
        ),
        migrations.AlterField(
            model_name='series',
            name='tags',
            field=models.ManyToManyField(to='semantictags.Tag'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='tags',
            field=models.ManyToManyField(to='semantictags.Tag'),
        ),
    ]
