# Generated by Django 2.1.3 on 2019-06-22 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retconpeople', '0006_website_parent_site'),
        ('retconcreatives', '0006_auto_20190622_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='retconpeople.Website'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='parent_studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_studios', to='retconcreatives.Studio'),
        ),
    ]
