# Generated by Django 2.1.3 on 2019-09-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0009_auto_20190920_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='order_in_series',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='episode',
            name='previous_episode',
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('part_of', 'order_in_series')},
        ),
    ]
