# Generated by Django 2.1.1 on 2019-10-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedstrings', '0005_auto_20190922_1607'),
        ('retconcreatives', '0013_auto_20190920_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativework',
            name='ambiguous_tags',
            field=models.ManyToManyField(blank=True, to='sharedstrings.Strings'),
        ),
        migrations.AddField(
            model_name='studio',
            name='ambiguous_tags',
            field=models.ManyToManyField(blank=True, to='sharedstrings.Strings'),
        ),
    ]
