# Generated by Django 2.1.1 on 2019-11-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0015_auto_20191112_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativework',
            name='published_by',
            field=models.ManyToManyField(blank=True, related_name='published', to='retconcreatives.Company'),
        ),
        migrations.AddField(
            model_name='series',
            name='produced_by',
            field=models.ManyToManyField(blank=True, related_name='produced', to='retconcreatives.Company'),
        ),
    ]
