# Generated by Django 2.1.1 on 2019-11-12 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0016_auto_20191112_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.PositiveSmallIntegerField(choices=[(0, 'adaptation'), (1, 'spinoff'), (2, 'sequel')], help_text='e.g. <to_work> is a sequel to <from_work>')),
            ],
        ),
        migrations.AlterField(
            model_name='creativework',
            name='published_by',
            field=models.ManyToManyField(blank=True, related_name='published_creativework', to='retconcreatives.Company'),
        ),
        migrations.AlterField(
            model_name='series',
            name='parent_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_series', to='retconcreatives.Series'),
        ),
        migrations.AddField(
            model_name='relatedseries',
            name='from_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='based_off', to='retconcreatives.Series'),
        ),
        migrations.AddField(
            model_name='relatedseries',
            name='to_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='retconcreatives.Series'),
        ),
        migrations.AddField(
            model_name='series',
            name='related_series',
            field=models.ManyToManyField(related_name='series_related', through='retconcreatives.RelatedSeries', to='retconcreatives.Series'),
        ),
    ]
