# Generated by Django 2.1.3 on 2019-12-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotables', '0002_auto_20191214_0848'),
        ('retconcreatives', '0021_merge_20191124_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativework',
            name='external_representation',
            field=models.ManyToManyField(blank=True, related_name='_creativework_external_representation_+', to='remotables.ContentResource'),
        ),
    ]
