# Generated by Django 2.1.3 on 2020-01-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0025_auto_20200105_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
