# Generated by Django 2.1.3 on 2020-06-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0029_auto_20200610_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativework',
            name='published_on_precision',
            field=models.CharField(blank=True, choices=[('y', 'Year'), ('m', 'Month'), ('d', 'Day')], max_length=1, null=True),
        ),
    ]
