# Generated by Django 2.1.3 on 2020-07-31 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0032_auto_20200731_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='part_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='episodes', to='retconcreatives.Series'),
        ),
    ]
