# Generated by Django 2.2.28 on 2023-07-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0040_auto_20230715_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='creativework',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
