# Generated by Django 2.2.28 on 2023-07-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0041_auto_20230715_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='production_code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
