# Generated by Django 2.1.3 on 2019-06-18 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sharedstrings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('definition', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TagLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sharedstrings.Strings')),
                ('language_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sharedstrings.Strings')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='labels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='definitions', to='semantictags.TagLabel'),
        ),
    ]
