# Generated by Django 2.1.3 on 2019-09-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantictags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='labels',
        ),
        migrations.AddField(
            model_name='tag',
            name='labels',
            field=models.ManyToManyField(related_name='definitions', to='semantictags.TagLabel'),
        ),
    ]
