# Generated by Django 2.1.3 on 2019-09-20 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semantictags', '0004_auto_20190920_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='canonical_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='semantictags.TagLabel'),
        ),
    ]
