# Generated by Django 2.1.1 on 2019-10-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantictags', '0006_auto_20190922_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='distinguish_from',
            field=models.ManyToManyField(blank=True, related_name='_tag_distinguish_from_+', to='semantictags.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='implies',
            field=models.ManyToManyField(blank=True, related_name='implied_by', to='semantictags.Tag'),
        ),
    ]
