# Generated by Django 2.1.3 on 2020-07-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantictags', '0009_auto_20191228_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='conflicts_with',
            field=models.ManyToManyField(blank=True, help_text='x &#8853; y', related_name='_tag_conflicts_with_+', to='semantictags.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='distinguish_from',
            field=models.ManyToManyField(blank=True, help_text='this ≠ that', related_name='_tag_distinguish_from_+', to='semantictags.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='implies',
            field=models.ManyToManyField(blank=True, help_text='this &Implies; that', related_name='implied_by', to='semantictags.Tag'),
        ),
    ]
