# Generated by Django 2.1.3 on 2019-09-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedstrings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strings',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
