# Generated by Django 2.1.3 on 2019-11-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedstrings', '0007_auto_20191118_1107'),
        ('sharedstrings', '0007_auto_20191116_1603'),
    ]

    operations = [
    ]
