# Generated by Django 2.2.28 on 2022-08-21 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedstrings', '0008_merge_20191124_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strings',
            name='name',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.ProhibitNullCharactersValidator, django.core.validators.RegexValidator('(?:\\S*.*\\S|\\S)')]),
        ),
    ]
