# Generated by Django 2.2.14 on 2021-10-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotables', '0006_auto_20211008_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentresource',
            name='url',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='ephemeralresource',
            name='url',
            field=models.CharField(max_length=2000),
        ),
    ]
