# Generated by Django 2.2.28 on 2022-08-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotables', '0007_auto_20211008_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentresource',
            name='url',
            field=models.CharField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='ephemeralresource',
            name='url',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
