# Generated by Django 2.2.14 on 2020-09-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotables', '0003_auto_20200731_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentresource',
            name='url',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='ephemeralresource',
            name='url',
            field=models.CharField(max_length=2000),
        ),
    ]
