# Generated by Django 2.2.14 on 2020-09-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotables', '0004_auto_20200902_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentresource',
            name='url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='ephemeralresource',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
