# Generated by Django 2.2.14 on 2021-10-08 20:10

from datetime import time
from django.db import migrations, models
from django.utils import timezone

def forwards_func(apps, schema_editor):
    '''If any datetime field is null, just make it now'''
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    ContentResource = apps.get_model("remotables", "ContentResource")
    EphemeralResource = apps.get_model("remotables", "EphemeralResource")
    now=timezone.now()
    ContentResource.objects.filter(added_at__isnull=True).update(added_at=now)
    EphemeralResource.objects.filter(added_at__isnull=True).update(added_at=now)

class Migration(migrations.Migration):

    dependencies = [
        ('remotables', '0005_auto_20200906_2030'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.AlterField(
            model_name='contentresource',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ephemeralresource',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
