# Generated by Django 2.1.3 on 2019-09-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedstrings', '0002_auto_20190920_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Language name')),
                ('name_local', models.CharField(blank=True, default='', max_length=256, verbose_name='Language name (in that language)')),
                ('isocode', models.CharField(help_text='2 character language code without country', max_length=2, unique=True, verbose_name='ISO 639-1 Language code')),
                ('sorting', models.PositiveIntegerField(default=0, help_text='increase to show at top of the list', verbose_name='sorting order')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
                'ordering': ('-sorting', 'name', 'isocode'),
            },
        ),
    ]
