# Generated by Django 2.1.3 on 2019-09-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedstrings', '0004_auto_20190920_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='isocode',
            field=models.CharField(help_text='2 character language code without country', max_length=7, unique=True, verbose_name='ISO 639-1 Language code'),
        ),
    ]
