# Generated by Django 2.1.1 on 2019-11-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedstrings', '0005_auto_20190922_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strings',
            options={'verbose_name_plural': 'strings'},
        ),
    ]
