# Generated by Django 2.1.3 on 2019-11-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedstrings', '0006_auto_20191112_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strings',
            options={},
        ),
    ]
