# Generated by Django 2.2.14 on 2020-09-02 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semantictags', '0011_auto_20200817_0105'),
        ('retconstorage', '0007_auto_20200612_2121'),
        ('retconpeople', '0029_auto_20200828_0302'),
        ('sharedstrings', '0008_merge_20191124_1653'),
        ('remotables', '0004_auto_20200902_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_body', models.TextField(blank=True, editable=False, null=True)),
                ('json_body', models.TextField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, editable=False, max_length=256, null=True)),
                ('timestamp', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ambiguous_tags', models.ManyToManyField(blank=True, related_name='_post_ambiguous_tags_+', to='sharedstrings.Strings')),
                ('attachements', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='retconstorage.Collection')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='retconpeople.Person')),
                ('tags', models.ManyToManyField(blank=True, to='semantictags.Tag')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remotables.ContentResource')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='retconpeople.Website')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
