# Generated by Django 2.1.3 on 2019-06-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedstrings', '0001_initial'),
        ('retconpeople', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pseudonyms',
            field=models.ManyToManyField(to='sharedstrings.Strings'),
        ),
    ]
