# Generated by Django 2.1.3 on 2019-06-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantictags', '0001_initial'),
        ('retconpeople', '0002_person_pseudonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(related_name='_person_tags_+', to='semantictags.Tag'),
        ),
        migrations.AddField(
            model_name='username',
            name='tags',
            field=models.ManyToManyField(related_name='_username_tags_+', to='semantictags.Tag'),
        ),
        migrations.AddField(
            model_name='website',
            name='tags',
            field=models.ManyToManyField(related_name='_website_tags_+', to='semantictags.Tag'),
        ),
    ]
