# Generated by Django 2.1.3 on 2019-06-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retconpeople', '0003_auto_20190618_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='user_name_pattern',
            new_name='username_pattern',
        ),
    ]
