# Generated by Django 2.1.3 on 2019-06-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedstrings', '0001_initial'),
        ('retconpeople', '0004_auto_20190618_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernumber',
            name='number',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='username',
            unique_together={('website', 'name')},
        ),
        migrations.RemoveField(
            model_name='usernumber',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='usernumber',
            unique_together={('website', 'number')},
        ),
    ]
