# Generated by Django 2.1.3 on 2019-06-22 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retconpeople', '0005_auto_20190622_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='parent_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_sites', to='retconpeople.Website'),
        ),
    ]
