# Generated by Django 2.1.3 on 2019-09-20 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retconpeople', '0006_website_parent_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usernames', to='retconpeople.Person'),
        ),
        migrations.AddField(
            model_name='usernumber',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_numbers', to='retconpeople.Person'),
        ),
    ]
