# Generated by Django 2.1.3 on 2019-12-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconpeople', '0016_person_external_representation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='external_representation',
            field=models.ManyToManyField(blank=True, related_name='_person_external_representation_+', to='remotables.ContentResource'),
        ),
    ]
