# Generated by Django 2.1.3 on 2019-12-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconpeople', '0017_auto_20191214_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='domain',
            field=models.CharField(help_text='e.g. twitter.com', max_length=256, unique=True),
        ),
    ]
