# Generated by Django 2.1.3 on 2020-04-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconpeople', '0021_person_uuid_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='role',
            field=models.IntegerField(blank=True,choices=[(None, '?'), (0, 'SFW'), (1, 'NSFW'), (2, 'NSFW Extreme')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='username',
            name='status',
            field=models.IntegerField(blank=True,choices=[(None, '?'), (0, 'Active'), (1, 'Inactive'), (2, 'Dead')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='usernumber',
            name='role',
            field=models.IntegerField(blank=True,choices=[(None, '?'), (0, 'SFW'), (1, 'NSFW'), (2, 'NSFW Extreme')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='usernumber',
            name='status',
            field=models.IntegerField(blank=True,choices=[(None, '?'), (0, 'Active'), (1, 'Inactive'), (2, 'Dead')], default=None, null=True),
        ),
    ]
