# Generated by Django 2.1.3 on 2020-06-30 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retconpeople', '0023_auto_20200604_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=1024)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_patterns', to='retconpeople.Website')),
            ],
        ),
        migrations.AddField(
            model_name='username',
            name='wanted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernumber',
            name='wanted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
