# Generated by Django 2.1.3 on 2020-06-30 10:21

from django.db import migrations

def extract_user_identifiers(apps, schema_editor):
        # We get the model from the versioned app registry;
        # if we directly import it, it'll be the wrong version
        Website = apps.get_model("retconpeople", "Website")
        URLPattern = apps.get_model("retconpeople", "UrlPattern")
        for w in Website.objects.all():
            if w.user_number_pattern is not None:
                URLPattern(website=w,pattern=w.user_number_pattern).save()
            if w.username_pattern is not None:
                URLPattern(website=w,pattern=w.username_pattern).save()

class Migration(migrations.Migration):

    dependencies = [
        ('retconpeople', '0024_auto_20200630_1016'),
    ]
    operations = [
        migrations.RunPython(extract_user_identifiers),
    ]
    

