# Generated by Django 2.1.3 on 2020-07-31 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retconpeople', '0027_person_distinguish_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='distinguish_from',
            field=models.ManyToManyField(blank=True, help_text='Indicate people of similar names who should not be confused', related_name='_person_distinguish_from_+', to='retconpeople.Person'),
        ),
        migrations.AlterField(
            model_name='usernumber',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_numbers', to='retconpeople.Person'),
        ),
        migrations.AlterField(
            model_name='usernumber',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_numbers', to='retconpeople.Website'),
        ),
    ]
