# Generated by Django 2.2.28 on 2022-08-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconpeople', '0034_auto_20211013_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='status',
            field=models.IntegerField(blank=True, choices=[(None, ''), (0, 'Active'), (1, 'Inactive'), (2, 'Dead'), (3, 'Suspended'), (4, 'Private')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='username',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='_username_tags_+', to='semantictags.Tag'),
        ),
        migrations.AlterField(
            model_name='usernumber',
            name='status',
            field=models.IntegerField(blank=True, choices=[(None, ''), (0, 'Active'), (1, 'Inactive'), (2, 'Dead'), (3, 'Suspended'), (4, 'Private')], default=None, null=True),
        ),
    ]
