# Generated by Django 2.2.28 on 2023-07-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedstrings', '0009_auto_20220821_0125'),
        ('retconpeople', '0035_auto_20220821_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_favourite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.TextField(default=None, max_length=512, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='website',
            name='ambiguous_tags',
            field=models.ManyToManyField(blank=True, related_name='_website_ambiguous_tags_+', to='sharedstrings.Strings'),
        ),
        migrations.AddField(
            model_name='website',
            name='is_favourite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='website',
            name='notes',
            field=models.TextField(default=None, max_length=512, null=True, blank=True),
        ),
    ]
