# Generated by Django 2.1.3 on 2020-01-05 06:27

from django.db import migrations, models
import django.db.models.deletion
import retconstorage.fields
import retconstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='retconstorage.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='ManagedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', retconstorage.fields.HashFileField(storage=retconstorage.storage.HashStorage(), upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='contents',
            field=models.ManyToManyField(blank=True, to='retconstorage.ManagedFile'),
        ),
        migrations.AddField(
            model_name='collection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='retconstorage.Collection'),
        ),
    ]
