# Generated by Django 2.1.3 on 2020-06-10 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retconstorage', '0003_namedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filetype',
            options={'ordering': ('MIME',)},
        ),
        migrations.AlterField(
            model_name='managedfile',
            name='filetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='retconstorage.Filetype'),
        ),
        migrations.AlterField(
            model_name='namedfile',
            name='identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='retconstorage.ManagedFile'),
        ),
        migrations.AddIndex(
            model_name='managedfile',
            index=models.Index(fields=['filetype'], name='retconstora_filetyp_239701_idx'),
        ),
    ]
