# Generated by Django 2.1.3 on 2019-06-22 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0003_auto_20190622_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='previous_episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_episode', to='retconcreatives.Episode'),
        ),
    ]
