# Generated by Django 2.1.3 on 2019-06-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantictags', '0001_initial'),
        ('retconcreatives', '0004_episode_previous_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativework',
            name='tags',
            field=models.ManyToManyField(related_name='retconcreatives_creativework_related', related_query_name='retconcreatives_creativeworks', to='semantictags.Tag'),
        ),
        migrations.AddField(
            model_name='series',
            name='tags',
            field=models.ManyToManyField(related_name='retconcreatives_series_related', related_query_name='retconcreatives_seriess', to='semantictags.Tag'),
        ),
        migrations.AddField(
            model_name='studio',
            name='tags',
            field=models.ManyToManyField(related_name='retconcreatives_studio_related', related_query_name='retconcreatives_studios', to='semantictags.Tag'),
        ),
    ]
