# Generated by Django 2.1.3 on 2019-09-20 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0010_auto_20190920_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='id',
        ),
        migrations.RemoveField(
            model_name='series',
            name='tags',
        ),
        migrations.AddField(
            model_name='series',
            name='creativework_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='retconcreatives.CreativeWork'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creativework',
            name='tags',
            field=models.ManyToManyField(blank=True, to='semantictags.Tag'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='tags',
            field=models.ManyToManyField(blank=True, to='semantictags.Tag'),
        ),
    ]
