# Generated by Django 2.1.3 on 2019-09-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0012_auto_20190920_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
