# Generated by Django 2.1.1 on 2019-11-12 13:27

from django.db import migrations, models
import django.db.models.deletion
import sharedstrings.models


class Migration(migrations.Migration):

    atomic=False
    dependencies = [
        ('sharedstrings', '0006_auto_20191112_1327'),
        ('retconpeople', '0012_auto_20191025_1332'),
        ('semantictags', '0007_auto_20191010_0008'),
        ('retconcreatives', '0014_auto_20191025_1332'),
    ]

    operations = [
        migrations.RenameModel('Studio','Company'),
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('creativework_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='retconcreatives.CreativeWork')),
                ('illustrators', models.ManyToManyField(to='retconpeople.Person')),
            ],
            options={
                'abstract': False,
            },
            bases=('retconcreatives.creativework',),
        ),
                migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'series'},
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='retconpeople.Person'),
        ),
        migrations.RenameField(model_name='company',old_name='parent_studio',new_name='parent'),
        migrations.AddField(
            model_name='series',
            name='parent_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='retconcreatives.Series'),
        ),
        migrations.AddField(
            model_name='software',
            name='platforms',
            field=models.ManyToManyField(blank=True, help_text='Platforms this sofware runs on including consoles and operating systems', related_name='_software_platforms_+', to='retconcreatives.Software'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=sharedstrings.models.SharedStringField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sharedstrings.Strings'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='retconpeople.Website'),
        ),
        migrations.AlterField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='retconcreatives.Company'),
        )
    ]
