# Generated by Django 2.1.3 on 2019-11-16 16:03

from django.db import migrations, models
import django.db.models.deletion
import sharedstrings.models


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0017_auto_20191112_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ambiguous_tags',
            field=models.ManyToManyField(blank=True, related_name='_company_ambiguous_tags_+', to='sharedstrings.Strings'),
        ),
        migrations.AlterField(
            model_name='creativework',
            name='ambiguous_tags',
            field=models.ManyToManyField(blank=True, related_name='_creativework_ambiguous_tags_+', to='sharedstrings.Strings'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=sharedstrings.models.SharedStringField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sharedstrings.Strings'),
        ),
        migrations.AlterField(
            model_name='series',
            name='related_series',
            field=models.ManyToManyField(related_name='related_from_series', through='retconcreatives.RelatedSeries', to='retconcreatives.Series'),
        ),
    ]
