# Generated by Django 2.1.3 on 2019-11-18 11:07

from django.db import migrations, models
import django.db.models.deletion
import sharedstrings.models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedstrings', '0007_auto_20191118_1107'),
        ('retconcreatives', '0017_auto_20191112_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='ambiguous_tags',
            field=models.ManyToManyField(blank=True, related_name='_company_ambiguous_tags_+', to='sharedstrings.Strings'),
        ),
        migrations.AlterField(
            model_name='creativework',
            name='ambiguous_tags',
            field=models.ManyToManyField(blank=True, related_name='_creativework_ambiguous_tags_+', to='sharedstrings.Strings'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=sharedstrings.models.SharedStringField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sharedstrings.Strings'),
        ),
        migrations.AlterField(
            model_name='series',
            name='related_series',
            field=models.ManyToManyField(related_name='related_from_series', through='retconcreatives.RelatedSeries', to='retconcreatives.Series'),
        ),
        migrations.AddField(
            model_name='title',
            name='creative_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localized_titles', to='retconcreatives.CreativeWork'),
        ),
        migrations.AddField(
            model_name='title',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sharedstrings.Language'),
        ),
    ]
