# Generated by Django 2.1.3 on 2019-12-29 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0022_creativework_external_representation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='part_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='retconcreatives.Series'),
        ),
    ]
