# Generated by Django 2.1.3 on 2020-04-16 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0026_episode_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name__name']},
        ),
    ]
