# Generated by Django 2.1.3 on 2020-06-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0027_auto_20200416_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='medium',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Anthology'), (2, 'Audio'), (3, 'Comic book / Manga'), (1, 'Book'), (4, 'Movie'), (6, 'Software'), (5, 'Television'), (7, 'Video Game'), (8, 'Webcomic'), (9, 'Webseries')], null=True),
        ),
    ]
