# Generated by Django 2.1.3 on 2020-06-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0028_series_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='medium',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Anthology'), (2, 'Audio'), (3, 'Comic book / Manga'), (1, 'Book'), (4, 'Movie'), (6, 'Software'), (5, 'Television'), (10, 'Cartoon / Anime'), (7, 'Video Game'), (8, 'Webcomic'), (9, 'Webseries'), (11, 'Web Cartoon')], null=True),
        ),
    ]
