# Generated by Django 2.1.3 on 2020-07-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0030_creativework_published_on_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='defunct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
