# Generated by Django 2.1.3 on 2020-07-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0031_company_defunct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='medium',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Anthology'), (2, 'Audio'), (3, 'Comic book / Manga'), (1, 'Book'), (4, 'Movie'), (6, 'Software'), (5, 'Television'), (7, 'Video Game'), (8, 'Webcomic'), (9, 'Webseries'), (11, 'Web Cartoon')]),
        ),
    ]
