# Generated by Django 2.2.13 on 2020-08-17 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0033_auto_20200731_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='reading_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retconcreatives.Book'),
        ),
        migrations.AlterField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='retconcreatives.Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='retconpeople.Website'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='retconcreatives.Genre'),
        ),
        migrations.AlterField(
            model_name='relatedseries',
            name='from_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='based_off', to='retconcreatives.Series'),
        ),
        migrations.AlterField(
            model_name='relatedseries',
            name='to_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retconcreatives.Series'),
        ),
    ]
