# Generated by Django 2.2.14 on 2020-08-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0034_auto_20200817_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='webvideo',
            name='production_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='case_sensitive_name',
            field=models.BooleanField(default=False),
        ),
    ]
