# Generated by Django 2.2.14 on 2020-08-28 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    '''This migration will fail if you previously had any web videos, but I don't vare because you shouldn't be usign lapha features.'''
    
    dependencies = [
        ('retconcreatives', '0035_auto_20200828_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('episode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='retconcreatives.Episode')),
                ('production_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('retconcreatives.episode',),
        ),
        migrations.RemoveField(
            model_name='webvideo',
            name='episode_ptr',
        ),
        migrations.RemoveField(
            model_name='webvideo',
            name='production_number',
        ),
        migrations.AddField(
            model_name='webvideo',
            name='recording_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='retconcreatives.Recording'),
            preserve_default=False,
        ),
    ]
