# Generated by Django 2.2.14 on 2021-09-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retconcreatives', '0038_auto_20200906_2030'),
        ('retconpeople', '0033_website_owner')
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
    ]
