# Generated by Django 2.1.3 on 2019-09-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantictags', '0002_auto_20190920_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taglabel',
            name='label',
            field=models.CharField(max_length=64),
        ),
    ]
