# Generated by Django 2.1.3 on 2019-09-20 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semantictags', '0003_auto_20190920_0940'),
        ('sharedstrings', '0004_auto_20190920_0951')
    ]

    operations = [
        migrations.AlterField(
            model_name='taglabel',
            name='language_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sharedstrings.Language'),
        ),
    ]
