# Generated by Django 2.1.3 on 2019-09-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semantictags', '0005_tag_canonical_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taglabel',
            old_name='language_code',
            new_name='language',
        ),
    ]
